In [569]:
using LinearAlgebra
using Optim, NLSolversBase, Random
using Statistics
using Dataframe

LoadError: ArgumentError: Package Dataframe not found in current path.
- Run `import Pkg; Pkg.add("Dataframe")` to install the Dataframe package.

In [425]:
function onehotencoder(y::Vector{Int64})
    n = size(y,1)
    unique_val = unique(y)

    m = size(unique_val, 1)
    
    y_onehot = zeros(Int64, n,m)
    for i in 1:m
        loc = findall(x -> x==unique_val[i],y)
        y_onehot[loc, i] .= 1
    end
    return y_onehot
end

onehotencoder (generic function with 1 method)

In [384]:
y = rand(1:3,50);
t = zeros(50,5);
t[1,2] = 5

5

In [439]:
function softmax(z)
    s = zeros(size(z))
    for i in 1:size(z,1)
        s[i,:] = exp.(z[i,:])/sum(exp.(z[i,:]))
    end
    return s
end

softmax (generic function with 1 method)

In [406]:
p = rand(1:9,2,2)
println(p)
mean(p)

[4 5; 8 4]


5.25

In [553]:
x = rand(500,3)
w = rand(3,3)

y = rand(1:3,500)
likelihood_gradient(x,y,w,0.1)
# x*w

3×3 Matrix{Float64}:
 -0.0393785   0.0744798   0.240438
  0.141237   -0.00721509  0.088684
  0.113323    0.127044    0.213803

In [505]:
function likelihood(x,y::Vector{Int64},w, μ)
    y_onehot = onehotencoder(y)
    n,m = size(x)
    Z = -x*w
    p = softmax(Z)    
    
    return 1/n * ( tr( (x * w * transpose(y_onehot)) ) + sum(log(sum(exp.(Z))))) + μ*norm(w)^2
end

likelihood (generic function with 2 methods)

In [560]:
function likelihood_gradient(X,Y,W,μ)
    n,m = size(x)
    P = softmax(-X*W)
    Y_oh = onehotencoder(Y)
    grad = 1/n * ( transpose(X) *( Y_oh - P ) ) + 2*μ*W
end

likelihood_gradient (generic function with 1 method)

In [566]:
res = optimize(var -> likelihood(x,y,var,0.1),var -> likelihood_gradient(x,y,var,0.1), zeros(3,3), BFGS(); inplace = false)

 * Status: success (objective increased between iterations)

 * Candidate solution
    Final objective value:     1.179180e-02

 * Found with
    Algorithm:     BFGS

 * Convergence measures
    |x - x'|               = 2.29e-07 ≰ 0.0e+00
    |x - x'|/|x'|          = 4.05e-06 ≰ 0.0e+00
    |f(x) - f(x')|         = 2.59e-09 ≰ 0.0e+00
    |f(x) - f(x')|/|f(x')| = 2.20e-07 ≰ 0.0e+00
    |g(x)|                 = 1.20e-11 ≤ 1.0e-08

 * Work counters
    Seconds run:   3  (vs limit Inf)
    Iterations:    36
    f(x) calls:    1687
    ∇f(x) calls:   1687


In [567]:
w_res = Optim.minimizer(res)

3×3 Matrix{Float64}:
 0.0564475  -0.0418635   -0.0145841
 0.0354878  -0.00544324  -0.0300446
 0.0157258   0.0229508   -0.0386766

In [568]:
softmax(x * w_res)

500×3 Matrix{Float64}:
 0.351655  0.332214  0.316131
 0.347145  0.3265    0.326355
 0.358637  0.322947  0.318416
 0.357288  0.323458  0.319254
 0.364301  0.32046   0.315239
 0.344981  0.331136  0.323883
 0.338195  0.337443  0.324362
 0.357492  0.329589  0.312918
 0.359891  0.324974  0.315134
 0.367779  0.324761  0.307461
 0.347909  0.337047  0.315045
 0.350973  0.335442  0.313585
 0.355839  0.327534  0.316628
 ⋮                   
 0.356351  0.331139  0.31251
 0.361972  0.325472  0.312555
 0.35978   0.329728  0.310492
 0.35193   0.32929   0.31878
 0.360149  0.324423  0.315429
 0.355383  0.323218  0.321399
 0.348904  0.335452  0.315643
 0.351762  0.322033  0.326205
 0.365328  0.319043  0.315629
 0.348759  0.33227   0.318972
 0.354613  0.329458  0.315929
 0.351205  0.322535  0.32626

In [77]:
z = [0.1 0.2 0.4; 0.1 0.1 0.3; 0.1 0.1 0.3]

3×3 Matrix{Float64}:
 0.1  0.2  0.4
 0.1  0.1  0.3
 0.1  0.1  0.3

In [73]:
@time softmax(z)

  0.000010 seconds (11 allocations: 912 bytes)


2×3 Matrix{Float64}:
 0.289433  0.319873  0.390694
 0.310424  0.310424  0.379152

In [74]:
z2 = sum(softmax(z)[1,:])

1.0

In [75]:
n,m = size(z)

(2, 3)

In [83]:
transpose(z)

3×3 transpose(::Matrix{Float64}) with eltype Float64:
 0.1  0.1  0.1
 0.2  0.1  0.1
 0.4  0.3  0.3

In [1]:
using Pkg

In [3]:
using Optim

In [4]:
rosenbrock(x) =  (1.0 - x[1])^2 + 100.0 * (x[2] - x[1]^2)^2

rosenbrock (generic function with 1 method)

In [13]:
rosenbrock(ones(2)*2)

401.0

In [30]:
result = optimize(rosenbrock, zeros(2), BFGS())

 * Status: success

 * Candidate solution
    Final objective value:     5.471433e-17

 * Found with
    Algorithm:     BFGS

 * Convergence measures
    |x - x'|               = 3.47e-07 ≰ 0.0e+00
    |x - x'|/|x'|          = 3.47e-07 ≰ 0.0e+00
    |f(x) - f(x')|         = 6.59e-14 ≰ 0.0e+00
    |f(x) - f(x')|/|f(x')| = 1.20e+03 ≰ 0.0e+00
    |g(x)|                 = 2.33e-09 ≤ 1.0e-08

 * Work counters
    Seconds run:   0  (vs limit Inf)
    Iterations:    16
    f(x) calls:    53
    ∇f(x) calls:   53


In [31]:
Optim.minimizer(result)

2-element Vector{Float64}:
 0.9999999926033423
 0.9999999852005355

In [241]:

Random.seed!(0);     

In [161]:
function sigmoid(z)
    return 1 ./ (1+exp(-z))
end

sigmoid (generic function with 2 methods)

In [290]:
function Log_Likelihood(X::Matrix{Float64}, Y::Vector{Float64}, B::Vector{Float64})
    p = sigmoid.(X*B)
    ll = - dot(Y , log.(p)) - dot((1 .- Y) , log.(1 .- p))
end

Log_Likelihood (generic function with 4 methods)

In [291]:
n = 500                             # Number of observations
nvar = 2                            # Number of variables
B = ones(nvar) * 3.0                # True coefficients
x = [ones(n) randn(n, nvar - 1)]    # X matrix of explanatory variables plus constant
ε = randn(n) * 0.5                  # Error variance
y = convert.(Float64, (x * B) .> 2.9);                # Generate Data

In [292]:
y

500-element Vector{Float64}:
 1.0
 1.0
 0.0
 1.0
 0.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 0.0
 1.0
 ⋮
 1.0
 0.0
 0.0
 1.0
 1.0
 1.0
 1.0
 0.0
 1.0
 0.0
 1.0
 1.0

In [294]:
Log_Likelihood(x,y,B)

350.9469009334777

In [295]:
func = TwiceDifferentiable(vars -> Log_Likelihood(x, y, vars[1:nvar]), ones(nvar+1); autodiff=:forward);

In [303]:
opt = optimize(vars -> Log_Likelihood(x, y, vars[1:nvar]), ones(nvar+1), BFGS())

 * Status: success

 * Candidate solution
    Final objective value:     2.740536e+01

 * Found with
    Algorithm:     BFGS

 * Convergence measures
    |x - x'|               = 0.00e+00 ≤ 0.0e+00
    |x - x'|/|x'|          = 0.00e+00 ≤ 0.0e+00
    |f(x) - f(x')|         = 0.00e+00 ≤ 0.0e+00
    |f(x) - f(x')|/|f(x')| = 0.00e+00 ≤ 0.0e+00
    |g(x)|                 = 2.20e+00 ≰ 1.0e-08

 * Work counters
    Seconds run:   0  (vs limit Inf)
    Iterations:    6
    f(x) calls:    238
    ∇f(x) calls:   238


In [298]:
parameters = Optim.minimizer(opt)

3-element Vector{Float64}:
  0.14201085204025768
 12.451546421304174
 -8.084890187123765

In [299]:
sum((sigmoid.(x*parameters[1:nvar]) .> 0.5) .== y) / size(y,1)

0.99